FROM golang:1.23-bookworm AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o out/task-service ./cmd/task-service

FROM debian:bookworm-slim

WORKDIR /root/

COPY --from=builder /app/out/task-service .

EXPOSE 8080

CMD ["./task-service"]
